name: Create develop to main pull request

on:
  push:
    branches: [ develop ]
jobs:
  release-pull-request:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop
      - name: Use ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install git-pr-release
        run: gem install --no-document git-pr-release
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GIT_PR_RELEASE_APP_ID }}
          private-key: ${{ secrets.GIT_PR_RELEASE_PRIVATE_KEY }}
      - name: Run
        run: git-pr-release  --squashed
        env:
          GIT_PR_RELEASE_TOKEN: ${{ steps.generate_token.outputs.token }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TEMPLATE: .github/workflows/git-pr-release.erb
          TZ: Asia/Tokyo